# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: '**/DevOpsSample.WebApp'

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'use dotnet core cli'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(projectPath)'
        arguments: '-r linux-x64 -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: CopyFiles@2
      displayName: 'Copy scripts'
      inputs:
        contents: '*.json'
        targetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: test
  dependsOn: build
  jobs:
  - job: run_test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  #  - download: current
  #    artifact: drop
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        path: '$(Pipeline.Workspace)'
#    - powershell: Get-ChildItem $(Pipeline.Workspace) -Recurse
    - task: Bash@3
      inputs:
         targetType: 'inline'
         script: |
           # Write your commands here           
           ls -lha
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Pay-As-You-Go Dev/Test(d2b96e08-6110-47f7-bc0b-3475ac334617)'
        subscriptionId: 'd2b96e08-6110-47f7-bc0b-3475ac334617'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'devops'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/azuredeploy.json'
        deploymentMode: 'Incremental'