name: $(Rev:rrr) # This is not used since we define it during the first stage

pr: none

trigger: none

resources:
  pipelines:
    # Name of the pipeline resource inside this workflow. Used to reference the pipeline resources later on (e.g. download artifacts).
  - pipeline: package_build
    # Name of the pipeline in Azure Pipelines
    source: 'aca-devops-CI' 
    trigger: true

parameters:
- name: loggingLevel
  displayName: Logging Level
  type: string
  default: Pipeline
  values:
  - Pipeline
  - Debug

variables:
- template: ./variables/environments/environment-shared.yaml
- template: ./variables/release-information.yaml
- template: ./variables/apps/app-shared.yaml
- name: Pipeline.Version
  value: $(Artifact.Version)-$(Build.BuildNumber) 
- name: Artifact.Version
  value: $(resources.pipeline.package_build.runName)

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: preparation
  displayName: 'Prepare Deployment'
  jobs:
    - job: version
      displayName: Determine Version
      steps:
      - powershell: |
          Write-Host "##vso[build.updatebuildnumber]$(Pipeline.Version)"
          Write-Host "Pipeline version is '$(Pipeline.Version)'"
        displayName: 'Change pipeline version $(Pipeline.Version)'
- stage: deploy_development
  displayName: 'Deploy to Development'
  dependsOn: preparation
  variables:
    - template: ./variables/environments/environment-dev.yaml
    - template: ./variables/apps/app-dev.yaml
  jobs:
  - deployment: deploy_to_dev
    displayName: 'Deploy to DEV'
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - download: 'package_build'
            artifact: 'artifact'
            displayName: Download Artifact
          - template: ./templates/deploy-arm-template.yaml
            parameters:
              azureResourceManagerConnection: $(Azure.ServiceConnection.Name)
              subscriptionId: $(Azure.Subscription.Id)
              resourceGroupName: $(Azure.ResourceGroup.Name)
              location: $(Azure.ResourceGroup.Location)
              loggingLevel: ${{ parameters.loggingLevel }}

#- stage: deploy_production
#  displayName: 'Deploy to Production'
#  dependsOn: deploy_acceptance
#  variables:
#    - template: ./variables/environments/environment-prd.yaml
#    - template: ./variables/apps/app-prd.yaml
#  jobs:
#  - deployment: deploy_to_prd
#    displayName: 'Deploy to PRD'
#    environment: DevOps Skeleton (Production)
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - download: 'package_build'
#            artifact: 'artifact'
#            displayName: Download Artifact
#          - template: ./templates/deploy-arm-template.yaml
#            parameters:
#              azureResourceManagerConnection: $(Azure.ServiceConnection.Name)
#              subscriptionId: $(Azure.Subscription.Id)
#              resourceGroupName: $(Azure.ResourceGroup.Name)
#              location: $(Azure.ResourceGroup.Location)
#              loggingLevel: ${{ parameters.loggingLevel }}